version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    # volumes:
    #   - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    command: >
      rabbitmq-server
      --loader file
      --definitions /etc/rabbitmq/definitions.json

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --global-response-templating

  # app:
  #   build:
  ##     context: .
  #    dockerfile: Dockerfile
  #   container_name: insurance-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - rabbitmq
  #     - wiremock
